apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: registry.aliyuncs.com/google_containers/pause-amd64:3.1
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: v1.14.9
#apiServer:
#  certSANs:
#  - 192.168.10.10
controlPlaneEndpoint: "192.168.10.10:6443"
networking:
  podSubnet: 10.244.0.0/16
